### ISSUE TITLE
Formating goes wrong if apostrophe between backticks in comment.

### ISSUE THREAD

**Issue by divinerites** [theNewDynamic/language-hugo-vscode#22]
Problem with `d'accueil`

1 - double quote and with apostrophe = OK
```
{{ "<!-- Hero Area Image d'accueil -->" | safeHTML }}
```

2 - backticks and without apostrophe = OK
```
{{ `<!-- Hero Area Image d accueil -->` | safeHTML }}
```

3 - backticks and with apostrophe = Problem 
```
{{ `<!-- Hero Area Image d'accueil -->` | safeHTML }}
```

<img width="701" alt="Capture d’écran 2021-05-13 à 14 21 50" src="https://user-images.githubusercontent.com/32342823/118124945-9d75c580-b3f6-11eb-9170-9d6217bdf01a.png">

<img width="695" alt="Capture d’écran 2021-05-13 à 14 21 33" src="https://user-images.githubusercontent.com/32342823/118124950-9fd81f80-b3f6-11eb-84a0-3ccd04b4b6f7.png">

<img width="722" alt="Capture d’écran 2021-05-13 à 14 23 29" src="https://user-images.githubusercontent.com/32342823/118125100-d3b34500-b3f6-11eb-9b4a-423907c20934.png">

**Comment by budparr** [comment]
@divinerites the fix will be published shortly. Thanks for bringing it up!

**Comment by divinerites** [comment]
hey, thank YOU regis & bud for this great great tool.
It's a real corner case (and found thru a nasty hugo bug).  Nothing mainstream I guess :-)

**Comment by divinerites** [comment]
Hello, I updated to the v1.3.1. But it seems that it doesn't solve my exact use case. Not sure why.

<img width="1345" alt="Capture d’écran 2021-05-14 à 15 13 30" src="https://user-images.githubusercontent.com/32342823/118275829-3c69f280-b4c7-11eb-9bab-3fb2348b8e7e.png">
